### ISSUE TITLE
Doesn't work with 3.1-SNAPSHOT

### ISSUE THREAD

**Issue by Martoni** [ucb-bar/chisel-template#15]
I tested template «as it» and it working well, then I tested with last snapshot changing line in build.sbt : 
```
// Provide a managed dependency on X if -DXVersion="" is supplied on the command line.
val defaultVersions = Map(
  "chisel3" -> "3.1-SNAPSHOT",
  "chisel-iotesters" -> "1.1-SNAPSHOT"
  )
```

But got this error : 

```
[info] [0,007] Elaborating design...
[info] [0,135] Done elaborating.
[info] GCDTester:
[info] GCD
[info] Exception encountered when attempting to run a suite with class name: example.test.GCDTester *** ABORTED ***
[info]   java.lang.NoSuchMethodError: chisel3.internal.firrtl.Component.id()Lchisel3/core/Module;
[info]   at chisel3.iotesters.getTopModule$.apply(PeekPokeTesterUtils.scala:45)
[info]   at chisel3.iotesters.setupFirrtlTerpBackend$.apply(FirrtlTerpBackend.scala:112)
[info]   at chisel3.iotesters.Driver$$anonfun$execute$1.apply$mcZ$sp(Driver.scala:48)
[info]   at chisel3.iotesters.Driver$$anonfun$execute$1.apply(Driver.scala:35)
[info]   at chisel3.iotesters.Driver$$anonfun$execute$1.apply(Driver.scala:35)
[info]   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[info]   at chisel3.iotesters.Driver$.execute(Driver.scala:35)
[info]   at chisel3.iotesters.Driver$.apply(Driver.scala:212)
[info]   at example.test.GCDTester$$anonfun$2$$anonfun$apply$1.apply$mcV$sp(GCDUnitTest.scala:56)
[info]   at example.test.GCDTester$$anonfun$2$$anonfun$apply$1.apply(GCDUnitTest.scala:58)
[info]   ...
[info] ScalaCheck
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] ScalaTest
[info] Run completed in 1 second, 664 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 1
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[error] Error: Total 1, Failed 0, Errors 1, Passed 0
[error] Error during tests:
[error] 	example.test.GCDTester
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 3 s, completed 26 avr. 2017 14:06:02
```

**Comment by ucbjrl** [comment]
We have two main branches for each main Chisel project:

- `master`
- `release`

`master` is the main development branch and it is updated frequently (often several times a day). Although we endeavor to keep the master branches in sync, they may drift out of sync for a day or two. We do not publish the `master` branches. If you wish to use them, you need to clone the github repos and use `sbt publish-local` to make them available on your local machine.

The `release` branches are updated less often (currently bi-weekly) and we try to guarantee they are in sync. We publish these to Sonatype/Maven on a bi-weekly basis.

In general, you can not mix `release` and `master` branches and assume they will work.

The default branches for the user-facing repos ([chisel-template ](https://github.com/ucb-bar/chisel-template)and [chisel-tutorial](https://github.com/ucb-bar/chisel-tutorial)) are the `release` branches - these should always *just work* for new users as they use the `release` branches of chisel projects.

If you want to use something more current than the `release` branch, you should `git checkout master` for all the chisel repos you intend to use, then `sbt publish-local` them in this order:

- [firrtl](https://github.com/ucb-bar/firrtl)
- [firrtl-interpreter](https://github.com/ucb-bar/firrtl-interpreter)
- [chisel3](https://github.com/ucb-bar/chisel3)
- [chisel-testers](https://github.com/ucb-bar/chisel-testers)

Then, if you're working with the user-facing repos:
- [chisel-tutorial](https://github.com/ucb-bar/chisel-tutorial)
- [chisel-template ](https://github.com/ucb-bar/chisel-template)

Since this is a substantial amount of work (and has no guarantee of success), unless you are actively involved in Chisel development, we encourage you to stick with the `release` branches and their respective dependencies.

**Comment by Martoni** [comment]
Ok, thanks for this full explanation.

**Comment by ben-k** [comment]
@ucbjrl This explanation is very helpful and should be posted somewhere prominent IMHO.

**Comment by chick** [comment]
@ben-k I thought so too so I added it to the [Chisel3 Wiki FAQ](https://github.com/ucb-bar/chisel3/wiki/Frequently-Asked-Questions#What-is-the-difference-between-release-and-master-branches) yesterday

**Comment by ben-k** [comment]
Nope, that is perfect.
